<template>
  <section class="section" style="margin-bottom: 200px">
    <h2 class="title is-4 has-text-grey">
      Bagaimana Proses Pengembangan jendelakeu?
    </h2>
    <p>
      <img src="~/assets/alur.png">
    </p><br>
    Jendelakeu menggunakan format dokumen terstruktur dengan pendekatan <i>XBRL-Like Approach</i> yang memungkinkan laporan keuangan pemerintah dapat disajikan dengan sedemikian rupa. Hal ini berbeda dengan cara konvensional dimana umumnya laporan keunangan pemerintah disajikan dalam bentuk dokumen PDF.
    <br>
    <br>
    <h2 class="title is-4 has-text-grey">
      Apa itu XBRL?
    </h2>
    <p>
      XBRL atau Extensible Business Reporting Language, yang sebelumnya disebut
      XFRML, merupakan teknologi pelaporan bisnis yang dikembangkan untuk
      memfasilitasi komunikasi data keuangan secara elektronis. Penerapan XBRL
      memberikan solusi dari permasalahan-permasalahan dalam sistem pelaporan
      keuangan lama seperti validasi data secara manual, serta konversi dan
      mengekstrak data berjumlah besar. XBRL memungkinkan pengguna informasi
      keuangan melakukan analisa data dengan lebih mudah dan memudahkan
      penggunanya melakukan pembandingan antar informasi keuangan (Hoffman,
      2009).
    </p><br><p>
      Data laporan keuangan yang disajikan dalam XBRL dapat secara
      otomatis diolah oleh pengguna melalui perangkat lunak untuk selanjutnya
      dianalisis sesuai dengan spesifikasi dan keinginan mereka. XBRL membuat
      paradigma baru pelaporan keuangan dengan membuat data disajikan dalam
      format yang lebih interaktif. Hal ini dapat meningkatkan keefisienan dan
      kecepatan pemrosesan informasi, sekaligus meningkatkan kualitas keputusan
      melalui peningkatan konsistensi dan tingkat komparabilitas data (Baldwin,
      Brown dan Trinkle et al, 2006).Secara khusus, XBRL memiliki kelebihan
      karena proses tagging data informasi-informasi kontekstual dalam sebuah
      laporan keuangan. Tagging data secara sederhana dapat dipahami sebagai
      proses pemberian makna atau tanda tertentu pada sebuah komponen laporan
      keuangan yang dapat dibaca oleh komputer. Tagging data ini tidak hanya
      dapat diaplikasikan untuk data- data.
    </p>
    <br>
    <br>
    <p>  Di Indonesia, XBRL diterapkan di Bursa Efek Indonesia. Sebagai referensi silahkan membaca <a target="_blank" href="https://www.idx.co.id/perusahaan-tercatat/xbrl/"> <b> referensi ini </b> </a>.</p>
    <br>
    <h2 class="title is-4 has-text-grey">
      XBRL untuk Sektor Pemerintah
    </h2>
    <p>
      Penelitian dan pengembangan XBRL sendiri sebagian besar dominan berada pada sektor komersial. Padahal, terdapat peluang yang cukup besar terkait dengan pengembangan dan penelitian XBRL di sektor lain seperti sektor pemerintah untuk membantu meningkatkan pelayanan sektor publik dalam mengelola dan menyediakan data laporan keuangan (Perdana, 2015).
    </p>
    <br>
    <div class="notification">
      <i>
        “XBRL can help Government agencies bring in the required
        standardisation and discipline in regular reporting. XBRL to a large extent can
        insulate the quiality of the information generated by the reporting system from
        the complexities discussed. XBRL can also make the job consolidation at
        different project monitoring evels easier due to its structure. XBRL makes the
        data analytics ready” (Mohanty et al, 2012).</i>
    </div>
    <br>
    <p>
      Selain itu, Badan Pengawas Keuangan dan Pembangunan (BPKP) juga
      telah membuat kajian mengenai peluang penerapan XBRL untuk laporan
      keuangan pemerintah. Kajian teoritis tersebut menyatakan bahwa XBRL dapat
      menjadi solusi atas ketidakefisienan dalam pencarian informasi keuangan
      sektor publik dan dapat meningkatkan akuntabilitas dan transparansi
      pemerintah serta memfasilitasi pelaporan tunggal yang bersifat multipurposes.
    </p>
  </section>
</template>
